// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bougiebams-hero/GradientHero.tsx": () => import("../components/mockups/bougiebams-hero/GradientHero.tsx"),
  "./components/mockups/tile-shadows/DeepStacked.tsx": () => import("../components/mockups/tile-shadows/DeepStacked.tsx"),
  "./components/mockups/tile-shadows/FloatingGlow.tsx": () => import("../components/mockups/tile-shadows/FloatingGlow.tsx"),
  "./components/mockups/tile-shadows/LayeredOffset.tsx": () => import("../components/mockups/tile-shadows/LayeredOffset.tsx")
};
